.TH Yahtzee 6l
.SH NAME
yahtzee \- the game of Yahtzee
.SH SYNOPSIS
.B yahtzee
.B [\-nshfd]
.SH DESCRIPTION
.I Yahtzee
is a computer simulation of the game of the same name.
This version of
.I Yahtzee
allows up to six players, where
players can be either users at the same terminal
or a computer simulation of a player.
.PP
Full on\-line help is available at all times by pressing
the question mark character. If you are unfamiliar with
the rules a rule book is also available at all times
by pressing the 'b' key.
.PP
Options are:
.TP
.B  \-n
play
.I Yahtzee
non-stop, good if all players are computer simulations
.TP
.B  \-s
display the high score file
.TP
.B  \-h
give command line options
.TP
.B  \-f
don't sleep between simulation plays
.TP
.B  \-d
don't use the dim mode of the terminal (System 5)
.PP
At the end of each game the high score file is updated if necessary.
.SH BUGS
Unknown, but please send bug problems to {uunet,ucscc,decwrl,sun}!sco!staceyc
or staceyc@sco.com.
.SH AUTHOR
Stacey Campbell \- Santa Cruz, California, USA \- November 1989
